routes/web.php
<?php

 Route::get('/',function () {
    return view('frontend/home');
});
Route::redirect('/home', '/admin');

Auth::routes(['register' => true]);

    Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {
    Route::get('/', 'HomeController@index')->name('home');


    Route::delete('permissions/destroy', 'PermissionsController@massDestroy')->name('permissions.massDestroy');

    Route::resource('permissions', 'PermissionsController');

    Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');

    Route::resource('roles', 'RolesController');

    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');

    Route::resource('users', 'UsersController');

    Route::resource('kingqueen', 'KingQueenController');

    Route::delete('products/destroy', 'ProductsController@massDestroy')->name('products.massDestroy');

    Route::resource('products', 'ProductsController');


    Route::resource('years', 'YearsController');
    Route::delete('years/destroy', 'YearsController@massDestroy')->name('years.massDestroy');

    Route::resource('votedlist', 'VoltedListController');
    

     Route::resource('votedresult', 'VoltedResultController');
    

});
Route::redirect('/user', '/frontend');
Route::group(['prefix' => 'frontend', 'as' => 'frontend.', 'namespace' => 'Frontend', 'middleware' => ['auth']],  function () {
    
    Route::get('/', 'HomeController@index')->name('home');
     Route::resource('home', 'HomeController') ;
    Route::resource('login', 'LoginController');

    
     Route::resource('users', 'UsersController@index');

    Route::resource('kingqueen', 'KingQueenController');

   
});

app/Kingqueen.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Kingqueen extends Model
{
    //
     use SoftDeletes;

    protected $dates = [
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    protected $fillable = [
        'user_id',
        'type',
        'created_at',
        'updated_at',
        'deleted_at',
        'remember_token',
        'email_verified_at',
    ];
}

app/Http/Controllers/Admin/KingQueenController.php
<?php

namespace App\Http\Controllers\Admin;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Requests\MassDestroyUserRequest;
use App\Http\Requests\StoreUserRequest;
use App\Http\Requests\UpdateUserRequest;
use App\Role;
use App\User;
use App\Kingqueen;
use App\Product;
use DB;

class KingQueenController extends Controller
{
    //

     public function index( )
    {
        abort_unless(\Gate::allows('user_access'), 403);
          $query = 'select kingqueens.id,users.image,users.Name,kingqueens.roll,products.name from products join users join kingqueens on kingqueens.user_id=users.id and kingqueens.type=products.id';

          $kingqueen=\DB::select($query);
          
         return view('admin.kingqueen.index',compact('kingqueen'));
    
   
    }

    public function create( )
    {
        
        
         
        abort_unless(\Gate::allows('user_create'), 403);
         $query="select id,DATE_FORMAT(start_year, '%Y') as start_year,DATE_FORMAT(end_year, '%Y') as end_year from years order by id desc";
          $years=\DB::select($query);
          $query = 'select * from users';
          $users=\DB::select($query);
         $query = "select * from products where status='yes'";
          $products=\DB::select($query);
        
        return view('admin.kingqueen.create', compact('years','users','products' ));
    }

    public function store(Request $request)
    {
       
        abort_unless(\Gate::allows('user_create'), 403);
         
          $kingqueen=new kingqueen();
          $kingqueen->year_id=request('year_id');
          $kingqueen->user_id   =request('user_id');
          $kingqueen->type=request('product_id');
          $kingqueen->academic=request('academic_id');
          $kingqueen->roll=request('roll');
          $kingqueen->save();
       
        return redirect()->route('admin.kingqueen.index');
    }

    public function edit(Kingqueen $kingqueen)
    {

                
          $query="select id,DATE_FORMAT(start_year, '%Y') as start_year,DATE_FORMAT(end_year, '%Y') as end_year from years order by id desc";
          $years=\DB::select($query);
          $query = 'select * from users';
          $users=\DB::select($query);
          $query = "select * from products where status='yes'";
          $products=\DB::select($query);
          $id=$kingqueen->id;
          $year_idselected=$kingqueen->year_id;
          $user_idselected=$kingqueen->user_id;
          $product_idselected=$kingqueen->type;
          $academic_idselected=$kingqueen->academic;
          $roll=$kingqueen->roll;
        return view('admin.kingqueen.edit', compact('kingqueen','years','users', 'products','year_idselected','user_idselected','product_idselected','academic_idselected','roll'));
    }


    public function update(Request $request,Kingqueen $kingqueen )
     {
         
      
         $U_id=$kingqueen->id;
         $U_year_id=$request->year_id;
         $U_user_id=$request->user_id;
         $U_product_id=$request->product_id;
         $U_academic_id=$request->academic_id;
         $U_roll=$request->roll;

           $up=\DB::update('update kingqueens set  year_id = ?,user_id=?,type=?,academic=?,roll=? where id = ?',[$U_year_id,$U_user_id,$U_product_id,$U_academic_id,$U_roll,$U_id]);
         return redirect()->route('admin.kingqueen.index');
    }
  public function show(Kingqueen $kingqueen)
    {
        
           $query = 'select kingqueens.id,users.image,users.Name,kingqueens.roll,products.name from products join users join kingqueens on kingqueens.user_id=users.id and kingqueens.type=products.id where kingqueens.id=?';

           $kingqueeninfo=\DB::select($query,[$kingqueen->id]);

     //  dd($kingqueeninfo);
        return view('admin.kingqueen.show', compact('kingqueeninfo'));
    }
     

    public function destroy(Request $request,Kingqueen $kingqueen)
    {
        
 
       $query = 'delete  from kingqueens where id=?';
       $result=\DB::select($query,[$kingqueen->id]);
       $request->session()->flash('alert-success', 'Delete   successful  !');
 
        return back();
    }

    public function massDestroy(MassDestroyUserRequest $request)
    {
        User::whereIn('id', request('ids'))->delete();

        return response(null, 204);
    }
}

app/Http/Controllers/Frontend/KingQueenController.php
<?php

namespace App\Http\Controllers\frontend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Requests\MassDestroyUserRequest;
use App\Http\Requests\StoreUserRequest;
use App\Http\Requests\UpdateUserRequest;
use App\Role;
use App\User;
use App\Voted;
use DB;
class KingQueenController extends Controller
{
    //
    public function index(Request $request)
    {
    	   
         
             
            $hashed =DB::table('role_user')
                                 ->where('user_id', '=',\Auth::id())
                                 ->value('role_id');
            
         
            if($request->academic_year==null)
            {
                $academic_yearselected='1';
            }else
            {
                 $academic_yearselected=$request->academic_year; 
            }
             
            if($request->product==null)
            {
               $query = "select id from products where status='yes'";
               $products=\DB::select($query);
             
                $selectedproduct=$products[0]->id;
            }else
            {
                 $selectedproduct=$request->product; 
            }
         $query = "select * from products where status='yes'";
         $products=\DB::select($query);
         if(is_null($products))
         {
          dd('dfasfasd');
         }
         $query="select id,DATE_FORMAT(start_year, '%Y') as start_year,DATE_FORMAT(end_year, '%Y') as end_year from years order by start_year desc";
         $academic_years=\Db::select($query);
 
         $query="select * from voteds";
         $query = "select users.id,users.image,users.name,kingqueens.id as ID,kingqueens.type from products join users join kingqueens join years on kingqueens.user_id=users.id and kingqueens.type=products.id and kingqueens.year_id=years.id where  
            years.id=? and products.id=?  ";

          $kingqueens=\DB::select($query,[$academic_yearselected,$selectedproduct]);
         
        
        return view('frontend.main.kingqueen.index',compact('kingqueens', 'academic_years','products','academic_yearselected','selectedproduct','hashed'));
    }
     public function store(Request $request)
    {

          $query="select voteds.user_id,voteds.kingqueens_id,products.id from voteds join kingqueens join products on voteds.kingqueens_id=kingqueens.id and kingqueens.type=products.id";
          $voteds=\DB::select($query);
 
           $query="select id,DATE_FORMAT(start_year, '%Y') as start_year,DATE_FORMAT(end_year, '%Y') as end_year from years order by id desc";
          $years=\DB::select($query);
              
              for ($i=0; $i <sizeof($voteds) ; $i++)
               { 
                      if((\Auth::id()==$voteds[$i]->user_id && $request->kingqueen_id==$voteds[$i]->kingqueens_id) || (\Auth::id()==$voteds[$i]->user_id && $request->type==$voteds[$i]->id))
                       {
                             $request->session()->flash('alert-danger', 'User was already voted!');
                           return back();

                       } 
                }
          $voted=new voted();
          $voted->user_id   =\Auth::id();
          $voted->kingqueens_id=$request->kingqueen_id;
          $voted->save();
          $request->session()->flash('alert-success', 'User was successful voted!');
     
         return back();
    }
    public function show(Request $request)
    {        
            $hashed =DB::table('role_user')
                                 ->where('user_id', '=',\Auth::id())
                                 ->value('role_id');
            $query="select voteds.id,users.name,users.image,products.name as type from voteds join users join  kingqueens join products on voteds.kingqueens_id=kingqueens.id and kingqueens.user_id=users.id and kingqueens.type=products.id where voteds.user_id=?  ";
            $voted=\DB::select($query,[\Auth::id()]);
           
            
           return  view('frontend.main.kingqueen.show',compact('voted','hashed'));
    }
    public function destroy(Request $request)
    {
            
        
        $query = 'delete  from voteds where id=?';
        $result=\DB::select($query,[$request->id]);
          $request->session()->flash('alert-success', 'Delete   successful  !');
 
        return back();
    }

}

resources/views/frontend/main/kingqueen/index.blade.php
 @extends('layouts.menu')
 

@section('content')

<body id="page-top">

  <!-- Navigation -->
 
  <!-- Masthead -->
  
 <!-- Portfolio Section -->
  <div class=" p-b-34 p-t-100">
   <div class="card">
    <div class="card-header">
      
        <form  action="{{ route("frontend.kingqueen.index") }}" method="get"> 
               <div class="row">
                 <div class="col-sm-1" align="center">
               <label for="name">Academic*</label></div>
              <div class="col-sm-3" align="center" >
       <select   class="form-control" id="sel1" name="academic_year"  >
         
        @foreach($academic_years as $key => $academic_year)
                    <option value="{{ $academic_year->id  }}" {{($academic_year->id==$academic_yearselected)?'selected':''}}>{{$academic_year->start_year}} - {{$academic_year->end_year}} </option>  
                    @endforeach
      </select>  
    </div>
                
         
             <div class="col-sm-1" align="center">
               <label for="name">Type*</label></div>
              <div class="col-sm-3" align="center" >
       <select   class="form-control" id="sel1" name="product"  >
         
        @foreach($products as $key => $product)
                    <option value="{{ $product->id  }}" {{($product->id ==$selectedproduct)?'selected':''}}>{{$product->name}}</option>  
                    @endforeach
      </select>  
    </div>   
     
 <div class="col-sm-2" align="center">
   <button  type="submit" class="btn btn-success">search</button>
 </div>
 <div class="col-sm-2" align="center">
  <a class="btn btn-success"  href="{{ route("frontend.kingqueen.show",$selectedproduct) }}">voted List</a>
 </div>
</div>
</form>
 </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class=" table table-bordered table-striped table-hover datatable">
               <div class="flash-message">
    @foreach (['danger', 'warning', 'success', 'info'] as $msg)
      @if(Session::has('alert-' . $msg))

      <p class="alert alert-{{ $msg }}">{{ Session::get('alert-' . $msg) }} <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a></p>
      @endif
    @endforeach
  </div> 
                <tbody>
                             
                             <div class="row">
                               @foreach($kingqueens as $key => $kingqueen)
                               <form  action="{{ route("frontend.kingqueen.store") }}" method="POST" enctype="multipart/form-data">
                               @csrf
                               <div class="col-md-3">
                                
                            <div align="center" data-entry-id="{{ $kingqueen->id }}">
                                  <input type="hidden" name="id" value="{{ $kingqueen->id }}">
                                  <input type="hidden" name="type" value="{{ $kingqueen->type }}">
                                  <input type="hidden" name="kingqueen_id" value="{{ $kingqueen->ID }}">
                                  <img class="masthead-avatar mb-5" src=" {{ $kingqueen->image ?? '' }}" alt="" width="200px" height="200px" > <br>
                                  <span>{{ $kingqueen->name }} </span><br>
                                <input type="submit"  class="btn btn-xs btn-primary"   value=" {{ trans('global.king_queen.fields.vote') }}" >
                                     
                             
                          </div>
                        </div> 
                      </form>
                            @endforeach
                        
                            </div>

                         
                    
                </tbody>
            </table>
        </div>
    </div>

</div>
 </div>

@section('scripts')
@parent
<script>
    $(function () {
  let deleteButtonTrans = '{{ trans('global.datatables.delete') }}'
  let deleteButton = {
    text: deleteButtonTrans,
    url: "{{ route('admin.users.massDestroy') }}",
    className: 'btn-danger',
    action: function (e, dt, node, config) {
      var ids = $.map(dt.rows({ selected: true }).nodes(), function (entry) {
          return $(entry).data('entry-id')
      });

      if (ids.length === 0) {
        alert('{{ trans('global.datatables.zero_selected') }}')

        return
      }

      if (confirm('{{ trans('global.areYouSure') }}')) {
        $.ajax({
          headers: {'x-csrf-token': _token},
          method: 'POST',
          url: config.url,
          data: { ids: ids, _method: 'DELETE' }})
          .done(function () { location.reload() })
      }
    }
  }
  let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
@can('user_delete')
  dtButtons.push(deleteButton)
@endcan

  $('.datatable:not(.ajaxTable)').DataTable({ buttons: dtButtons })
})

</script>
@endsection
 

    

 
  
      
@endsection

resources/views/frontend/main/kingqueen/show.blade.php
 @extends('layouts.menu')
 

@section('content')

<body id="page-top">

  <!-- Navigation -->

 
  <!-- Masthead -->
  
 <!-- Portfolio Section -->
  <div class=" p-b-34 p-t-100">
<div class="card">
    <div class="card-header">
        {{ trans('global.show') }} {{ trans('global.user.title') }}
    </div>

    <div class="card-body">
        
                               
        <table class="table table-bordered table-striped">
            <tbody>
                <div class="flash-message">
    @foreach (['danger', 'warning', 'success', 'info'] as $msg)
      @if(Session::has('alert-' . $msg))

      <p class="alert alert-{{ $msg }}">{{ Session::get('alert-' . $msg) }} <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a></p>
      @endif
    @endforeach
  </div>
                <tr>
                     <th>Image</th>
                     <th>Name</th>
                     <th>Type</th>
                     <th>Action</th>
                </tr>
                @foreach($voted as $key => $voted)
                <tr>
                   
                    <td> <img src=" {{ $voted->image ?? '' }}" alt="" width="80px" height="80px" ></td>
                    <td>{{$voted->name}}</td>
                    <td>{{$voted->type}}</td>
                    <td>
                         
                                     <form action="{{ route('frontend.kingqueen.destroy', $voted->id) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
                                         <input type="hidden" name="id" value="{{$voted->id}}">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <input type="submit" class="btn btn-xs btn-danger" value="{{ trans('global.delete') }}">
                                    </form>
                                 
                    </td>
                    
                 </tr>
                 @endforeach
            </tbody>
        </table>
     
    </div>
</div>
</div>
</body>

@endsection